name: HeartoCast

on:
  schedule:
    - cron:
  workflow_dispatch:

jobs:
  shot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm init -y && npm install puppeteer
      - run: node shot.js
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
